### PR TITLE
fixed to export...

### PR DESCRIPTION
**Pull request by divinespear**
Quick fix for #33 and #84 
* fixed to export as plugin and global / single components. (it was broken :sob:)

### CODE REVIEW

**Comment by mika76** [comment]
@junedchhipa when do you think you will release a new npm package?

**Comment by junedchhipa** [comment]
Tomorrow

**Comment by mika76** [comment]
Works like a charm, thanks @divinespear and @junedchhipa !

**Comment by gmw-web** [comment]
Any updates on this new release @junedchhipa? 
The latest release appears to be 1.5.3, released on April 4th.

**Pull request merged**
